/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 27
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym__junk = 2,
  anon_sym_COLON = 3,
  aux_sym__rust_diag_token1 = 4,
  sym_message = 5,
  sym_source_ref = 6,
  sym__rust_error_code = 7,
  sym_lvl_error = 8,
  sym_lvl_warning = 9,
  sym_lvl_note = 10,
  sym_log = 11,
  sym_junk_lines = 12,
  sym__junk_line = 13,
  sym_diag = 14,
  sym__generic_diag = 15,
  sym__clang_diag = 16,
  sym__rust_diag = 17,
  sym__diag_level = 18,
  aux_sym_log_repeat1 = 19,
  aux_sym_junk_lines_repeat1 = 20,
  aux_sym__junk_line_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym__junk] = "_junk",
  [anon_sym_COLON] = ": ",
  [aux_sym__rust_diag_token1] = "_rust_diag_token1",
  [sym_message] = "message",
  [sym_source_ref] = "source_ref",
  [sym__rust_error_code] = "_rust_error_code",
  [sym_lvl_error] = "lvl_error",
  [sym_lvl_warning] = "lvl_warning",
  [sym_lvl_note] = "lvl_note",
  [sym_log] = "log",
  [sym_junk_lines] = "junk_lines",
  [sym__junk_line] = "_junk_line",
  [sym_diag] = "diag",
  [sym__generic_diag] = "_generic_diag",
  [sym__clang_diag] = "_clang_diag",
  [sym__rust_diag] = "_rust_diag",
  [sym__diag_level] = "_diag_level",
  [aux_sym_log_repeat1] = "log_repeat1",
  [aux_sym_junk_lines_repeat1] = "junk_lines_repeat1",
  [aux_sym__junk_line_repeat1] = "_junk_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym__junk] = sym__junk,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym__rust_diag_token1] = aux_sym__rust_diag_token1,
  [sym_message] = sym_message,
  [sym_source_ref] = sym_source_ref,
  [sym__rust_error_code] = sym__rust_error_code,
  [sym_lvl_error] = sym_lvl_error,
  [sym_lvl_warning] = sym_lvl_warning,
  [sym_lvl_note] = sym_lvl_note,
  [sym_log] = sym_log,
  [sym_junk_lines] = sym_junk_lines,
  [sym__junk_line] = sym__junk_line,
  [sym_diag] = sym_diag,
  [sym__generic_diag] = sym__generic_diag,
  [sym__clang_diag] = sym__clang_diag,
  [sym__rust_diag] = sym__rust_diag,
  [sym__diag_level] = sym__diag_level,
  [aux_sym_log_repeat1] = aux_sym_log_repeat1,
  [aux_sym_junk_lines_repeat1] = aux_sym_junk_lines_repeat1,
  [aux_sym__junk_line_repeat1] = aux_sym__junk_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym__junk] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__rust_diag_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_source_ref] = {
    .visible = true,
    .named = true,
  },
  [sym__rust_error_code] = {
    .visible = false,
    .named = true,
  },
  [sym_lvl_error] = {
    .visible = true,
    .named = true,
  },
  [sym_lvl_warning] = {
    .visible = true,
    .named = true,
  },
  [sym_lvl_note] = {
    .visible = true,
    .named = true,
  },
  [sym_log] = {
    .visible = true,
    .named = true,
  },
  [sym_junk_lines] = {
    .visible = true,
    .named = true,
  },
  [sym__junk_line] = {
    .visible = false,
    .named = true,
  },
  [sym_diag] = {
    .visible = true,
    .named = true,
  },
  [sym__generic_diag] = {
    .visible = false,
    .named = true,
  },
  [sym__clang_diag] = {
    .visible = false,
    .named = true,
  },
  [sym__rust_diag] = {
    .visible = false,
    .named = true,
  },
  [sym__diag_level] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_log_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_junk_lines_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__junk_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(39);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == 'e') ADVANCE(45);
      if (lookahead == 'n') ADVANCE(44);
      if (lookahead == 'w') ADVANCE(43);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '[') ADVANCE(22);
      if (lookahead == 'e') ADVANCE(34);
      if (lookahead == 'n') ADVANCE(30);
      if (lookahead == 'w') ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(48);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(47);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'e') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'g') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == ':') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == '>') ADVANCE(4);
      END_STATE();
    case 22:
      if (lookahead == 'E') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == ']') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 26:
      if (lookahead == 'g') ADVANCE(54);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 38:
      if (eof) ADVANCE(39);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == 'e') ADVANCE(45);
      if (lookahead == 'n') ADVANCE(44);
      if (lookahead == 'w') ADVANCE(43);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__junk);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__junk);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__junk);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__junk);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__junk);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym__rust_diag_token1);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_message);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_source_ref);
      if (lookahead == ':') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__rust_error_code);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_lvl_error);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_lvl_error);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_lvl_warning);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_lvl_warning);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_lvl_note);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_lvl_note);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 38},
  [2] = {.lex_state = 38},
  [3] = {.lex_state = 38},
  [4] = {.lex_state = 38},
  [5] = {.lex_state = 38},
  [6] = {.lex_state = 38},
  [7] = {.lex_state = 38},
  [8] = {.lex_state = 38},
  [9] = {.lex_state = 38},
  [10] = {.lex_state = 38},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 49},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 38},
  [20] = {.lex_state = 49},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 38},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 49},
  [26] = {.lex_state = 38},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym__junk] = ACTIONS(1),
    [aux_sym__rust_diag_token1] = ACTIONS(1),
    [sym_source_ref] = ACTIONS(1),
    [sym_lvl_error] = ACTIONS(1),
    [sym_lvl_warning] = ACTIONS(1),
    [sym_lvl_note] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_log] = STATE(17),
    [sym_junk_lines] = STATE(2),
    [sym__junk_line] = STATE(4),
    [sym_diag] = STATE(2),
    [sym__generic_diag] = STATE(6),
    [sym__clang_diag] = STATE(6),
    [sym__rust_diag] = STATE(6),
    [sym__diag_level] = STATE(14),
    [aux_sym_log_repeat1] = STATE(2),
    [aux_sym_junk_lines_repeat1] = STATE(4),
    [aux_sym__junk_line_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym__junk] = ACTIONS(7),
    [sym_source_ref] = ACTIONS(9),
    [sym_lvl_error] = ACTIONS(11),
    [sym_lvl_warning] = ACTIONS(11),
    [sym_lvl_note] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_junk_lines] = STATE(3),
    [sym__junk_line] = STATE(4),
    [sym_diag] = STATE(3),
    [sym__generic_diag] = STATE(6),
    [sym__clang_diag] = STATE(6),
    [sym__rust_diag] = STATE(6),
    [sym__diag_level] = STATE(14),
    [aux_sym_log_repeat1] = STATE(3),
    [aux_sym_junk_lines_repeat1] = STATE(4),
    [aux_sym__junk_line_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(5),
    [sym__junk] = ACTIONS(7),
    [sym_source_ref] = ACTIONS(9),
    [sym_lvl_error] = ACTIONS(11),
    [sym_lvl_warning] = ACTIONS(11),
    [sym_lvl_note] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_junk_lines] = STATE(3),
    [sym__junk_line] = STATE(4),
    [sym_diag] = STATE(3),
    [sym__generic_diag] = STATE(6),
    [sym__clang_diag] = STATE(6),
    [sym__rust_diag] = STATE(6),
    [sym__diag_level] = STATE(14),
    [aux_sym_log_repeat1] = STATE(3),
    [aux_sym_junk_lines_repeat1] = STATE(4),
    [aux_sym__junk_line_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_LF] = ACTIONS(17),
    [sym__junk] = ACTIONS(20),
    [sym_source_ref] = ACTIONS(23),
    [sym_lvl_error] = ACTIONS(26),
    [sym_lvl_warning] = ACTIONS(26),
    [sym_lvl_note] = ACTIONS(26),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(31), 1,
      anon_sym_LF,
    ACTIONS(34), 1,
      sym__junk,
    STATE(12), 1,
      aux_sym__junk_line_repeat1,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      sym_source_ref,
    STATE(5), 2,
      sym__junk_line,
      aux_sym_junk_lines_repeat1,
    ACTIONS(37), 3,
      sym_lvl_error,
      sym_lvl_warning,
      sym_lvl_note,
  [23] = 6,
    ACTIONS(41), 1,
      anon_sym_LF,
    ACTIONS(44), 1,
      sym__junk,
    STATE(12), 1,
      aux_sym__junk_line_repeat1,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      sym_source_ref,
    STATE(5), 2,
      sym__junk_line,
      aux_sym_junk_lines_repeat1,
    ACTIONS(47), 3,
      sym_lvl_error,
      sym_lvl_warning,
      sym_lvl_note,
  [46] = 2,
    ACTIONS(49), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_source_ref,
    ACTIONS(51), 4,
      sym__junk,
      sym_lvl_error,
      sym_lvl_warning,
      sym_lvl_note,
  [58] = 2,
    ACTIONS(53), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_source_ref,
    ACTIONS(55), 4,
      sym__junk,
      sym_lvl_error,
      sym_lvl_warning,
      sym_lvl_note,
  [70] = 2,
    ACTIONS(57), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_source_ref,
    ACTIONS(59), 4,
      sym__junk,
      sym_lvl_error,
      sym_lvl_warning,
      sym_lvl_note,
  [82] = 2,
    ACTIONS(61), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_source_ref,
    ACTIONS(63), 4,
      sym__junk,
      sym_lvl_error,
      sym_lvl_warning,
      sym_lvl_note,
  [94] = 2,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_source_ref,
    ACTIONS(67), 4,
      sym__junk,
      sym_lvl_error,
      sym_lvl_warning,
      sym_lvl_note,
  [106] = 2,
    STATE(21), 1,
      sym__diag_level,
    ACTIONS(69), 3,
      sym_lvl_error,
      sym_lvl_warning,
      sym_lvl_note,
  [115] = 3,
    ACTIONS(71), 1,
      anon_sym_LF,
    ACTIONS(73), 1,
      sym__junk,
    STATE(13), 1,
      aux_sym__junk_line_repeat1,
  [125] = 3,
    ACTIONS(75), 1,
      anon_sym_LF,
    ACTIONS(77), 1,
      sym__junk,
    STATE(13), 1,
      aux_sym__junk_line_repeat1,
  [135] = 2,
    ACTIONS(80), 1,
      anon_sym_COLON,
    ACTIONS(82), 1,
      sym__rust_error_code,
  [142] = 1,
    ACTIONS(84), 1,
      anon_sym_COLON,
  [146] = 1,
    ACTIONS(86), 1,
      sym_message,
  [150] = 1,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
  [154] = 1,
    ACTIONS(90), 1,
      anon_sym_COLON,
  [158] = 1,
    ACTIONS(92), 1,
      anon_sym_LF,
  [162] = 1,
    ACTIONS(94), 1,
      sym_message,
  [166] = 1,
    ACTIONS(96), 1,
      anon_sym_COLON,
  [170] = 1,
    ACTIONS(98), 1,
      aux_sym__rust_diag_token1,
  [174] = 1,
    ACTIONS(100), 1,
      anon_sym_LF,
  [178] = 1,
    ACTIONS(102), 1,
      sym_source_ref,
  [182] = 1,
    ACTIONS(104), 1,
      sym_message,
  [186] = 1,
    ACTIONS(106), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 23,
  [SMALL_STATE(6)] = 46,
  [SMALL_STATE(7)] = 58,
  [SMALL_STATE(8)] = 70,
  [SMALL_STATE(9)] = 82,
  [SMALL_STATE(10)] = 94,
  [SMALL_STATE(11)] = 106,
  [SMALL_STATE(12)] = 115,
  [SMALL_STATE(13)] = 125,
  [SMALL_STATE(14)] = 135,
  [SMALL_STATE(15)] = 142,
  [SMALL_STATE(16)] = 146,
  [SMALL_STATE(17)] = 150,
  [SMALL_STATE(18)] = 154,
  [SMALL_STATE(19)] = 158,
  [SMALL_STATE(20)] = 162,
  [SMALL_STATE(21)] = 166,
  [SMALL_STATE(22)] = 170,
  [SMALL_STATE(23)] = 174,
  [SMALL_STATE(24)] = 178,
  [SMALL_STATE(25)] = 182,
  [SMALL_STATE(26)] = 186,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_log, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_log, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_log_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_log_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_log_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_log_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_log_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_junk_lines, 1, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_junk_lines, 1, 0, 0), SHIFT(5),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_junk_lines, 1, 0, 0), SHIFT(12),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_junk_lines, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_junk_lines_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_junk_lines_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_junk_lines_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_junk_lines_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_diag, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_diag, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__junk_line, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__junk_line, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__generic_diag, 4, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__generic_diag, 4, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__clang_diag, 6, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__clang_diag, 6, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rust_diag, 7, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__rust_diag, 7, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__junk_line_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__junk_line_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [88] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_buildlog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "buildlog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
