/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 10
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 10
#define ALIAS_COUNT 0
#define TOKEN_COUNT 6
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_clang_diag2_token1 = 1,
  aux_sym_clang_diag2_token2 = 2,
  aux_sym_clang_diag2_token3 = 3,
  sym_arbitrary_text_no_newline = 4,
  anon_sym_LF = 5,
  sym_log = 6,
  sym_clang_diag2 = 7,
  sym_arbitrary_line = 8,
  aux_sym_log_repeat1 = 9,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_clang_diag2_token1] = "clang_diag2_token1",
  [aux_sym_clang_diag2_token2] = "clang_diag2_token2",
  [aux_sym_clang_diag2_token3] = "clang_diag2_token3",
  [sym_arbitrary_text_no_newline] = "arbitrary_text_no_newline",
  [anon_sym_LF] = "\n",
  [sym_log] = "log",
  [sym_clang_diag2] = "clang_diag2",
  [sym_arbitrary_line] = "arbitrary_line",
  [aux_sym_log_repeat1] = "log_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_clang_diag2_token1] = aux_sym_clang_diag2_token1,
  [aux_sym_clang_diag2_token2] = aux_sym_clang_diag2_token2,
  [aux_sym_clang_diag2_token3] = aux_sym_clang_diag2_token3,
  [sym_arbitrary_text_no_newline] = sym_arbitrary_text_no_newline,
  [anon_sym_LF] = anon_sym_LF,
  [sym_log] = sym_log,
  [sym_clang_diag2] = sym_clang_diag2,
  [sym_arbitrary_line] = sym_arbitrary_line,
  [aux_sym_log_repeat1] = aux_sym_log_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_clang_diag2_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_clang_diag2_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_clang_diag2_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_arbitrary_text_no_newline] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_log] = {
    .visible = true,
    .named = true,
  },
  [sym_clang_diag2] = {
    .visible = true,
    .named = true,
  },
  [sym_arbitrary_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_log_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == ':') ADVANCE(23);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == ':') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_clang_diag2_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_clang_diag2_token2);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_clang_diag2_token3);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_arbitrary_text_no_newline);
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_arbitrary_text_no_newline);
      if (lookahead == ':') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_arbitrary_text_no_newline);
      if (lookahead == ':') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_arbitrary_text_no_newline);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_arbitrary_text_no_newline);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_arbitrary_text_no_newline);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_clang_diag2_token1] = ACTIONS(1),
    [aux_sym_clang_diag2_token2] = ACTIONS(1),
    [sym_arbitrary_text_no_newline] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_log] = STATE(8),
    [sym_clang_diag2] = STATE(2),
    [sym_arbitrary_line] = STATE(2),
    [aux_sym_log_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_clang_diag2_token1] = ACTIONS(5),
    [sym_arbitrary_text_no_newline] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_clang_diag2] = STATE(3),
    [sym_arbitrary_line] = STATE(3),
    [aux_sym_log_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(9),
    [aux_sym_clang_diag2_token1] = ACTIONS(5),
    [sym_arbitrary_text_no_newline] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym_clang_diag2] = STATE(3),
    [sym_arbitrary_line] = STATE(3),
    [aux_sym_log_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [aux_sym_clang_diag2_token1] = ACTIONS(13),
    [sym_arbitrary_text_no_newline] = ACTIONS(16),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(21), 1,
      sym_arbitrary_text_no_newline,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      aux_sym_clang_diag2_token1,
  [8] = 2,
    ACTIONS(25), 1,
      sym_arbitrary_text_no_newline,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      aux_sym_clang_diag2_token1,
  [16] = 1,
    ACTIONS(27), 1,
      aux_sym_clang_diag2_token2,
  [20] = 1,
    ACTIONS(29), 1,
      anon_sym_LF,
  [24] = 1,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
  [28] = 1,
    ACTIONS(33), 1,
      aux_sym_clang_diag2_token3,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 8,
  [SMALL_STATE(6)] = 16,
  [SMALL_STATE(7)] = 20,
  [SMALL_STATE(8)] = 24,
  [SMALL_STATE(9)] = 28,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_log, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_log, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_log_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_log_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [16] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_log_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arbitrary_line, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arbitrary_line, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clang_diag2, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_clang_diag2, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [31] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_buildlog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "buildlog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
